services:
  - type: web
    name: sign-language-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run signapp.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
